### ISSUE TITLE
Alterações sobre padrões de código

### ISSUE THREAD

**Issue by gabrielrab** [hyperyuri/Sum-2-values#1]
## Pegar o valor
Seu código está com uma certa redundância, na parte:
```
var inputEl1 = document.getElementById("1");
var inputEl2 = document.getElementById("2");
var buttonEl = document.getElementById("3");

function soma(){

  const value1 = inputEl1.value;
  const value2 = inputEl2.value;
```
substitua por:
```
const inputEl1 = document.getElementById("1").value;
const inputEl2 = document.getElementById("2").value;
const buttonEl = document.getElementById("3").value;

function soma(){
   //continuação do código
```
## Métodos de captura de elementos:

Sugiro utilizar mais os métodos de captura de elementos como: `getElementByName`, `getElementByTagName` entre os outros. 
Observe a documentação:
https://www.w3schools.com/jsref/met_document_getelementsbyclassname.asp
https://www.w3schools.com/jsref/met_doc_getelementsbyname.asp
https://www.w3schools.com/jsref/met_document_getelementsbytagname.asp

A questão é que do modo que está funciona, porém não é semanticamente correto.

## Utilização correta de "id" e "classes"

Os `id`são utilizados para identificar um único elemento, e por convenção seu nome não deve começar ou ser somente um número. Do modo que está fica meio confuso e de difícil manutenção, principalmente se seu código expandir.

As classes são utilizadas para repetir um comportamento ou estilização em um determinado número de componentes pertencentes a ela. Por exemplo na estilização de CSS, os `<input/>` pertencem a mesma classe.

Um caso no seu código que ilustra a sua utilização errada de `classes` e `id` é no seu botão de submit, ele é único no seu código, ninguém será igual a ele, portanto ele não precisa de um id. Sugiro capture este elemento de outra forma.

## Inputs
No modo atual seus `<input/>` estão meio que incorretos, existe uma propriedade chamada `name`, com ela você consegue os diferenciar sem ter que utilizar os `id`, melhorando assim a semântica do seu código. 
Para pegar seu valor utilize por exemplo:
`var x = document.getElementsByName("animal")`
onde "animal" seria o nome passado dentro do atributo `name` do `<input/>`

**Comment by hyperyuri** [comment]
Realizei as alterações de getElement para querySelector, utilizando o name como parâmetro.  Adicionado uma class chamada "input" que foi adicionada aos 2, pois os dois devem ser iguais. No button summit foi removido o id e adicionado um name, codigo novo já está commitado
